// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    AppDrawer: typeof import('./src/components/layout/AppDrawer.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppImage: typeof import('./src/components/AppImage.vue')['default']
    AppNavbar: typeof import('./src/components/layout/AppNavbar.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    BoardDragAndDrop: typeof import('./src/components/BoardDragAndDrop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./src/components/TaskCard.vue')['default']
  }
}

export {}
